### ISSUE TITLE
TypeError: CreateListFromArrayLike called on non-object

### ISSUE THREAD

**Issue by Redsandro** [planttheidea/moize#116]
I occasionally see this on a live server. I don't know what causes it, and I cannot reproduce it on the dev server.

```
/app/node_modules/moize/lib/instance.js:66
    return ~keyIndex ? moized.apply(this, moized.cache.keys[keyIndex]) : undefined; // eslint-disable-line prefer-spread
                              ^
TypeError: CreateListFromArrayLike called on non-object
    at Function.moized.get (/app/node_modules/moize/lib/instance.js:66:31)
    at SMTPServer.<anonymous> (/app/utils/smtpServer.js:22:14)
    at SMTPServer.emit (events.js:210:5)
    at SMTPServer._onError (/app/node_modules/smtp-server/lib/smtp-server.js:346:14)
    at /app/node_modules/smtp-server/lib/smtp-server.js:85:41
    at TLSSocket.onError (/app/node_modules/smtp-server/lib/smtp-server.js:473:13)
    at Object.onceWrapper (events.js:300:26)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._tlsError (_tls_wrap.js:754:8)
    at TLSSocket.emit (events.js:215:7)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Moize 5.4.3. 

https://github.com/planttheidea/moize/blob/0c3f854d1507885e06b8cff9673a87dac558d68c/src/instance.js#L66-L70

All the code does is use `moizer` to sort-of debounce error messages (show them once, hide them for a week).

```javascript
const moizer = moize({
    maxAge: 7 * 24 * 3600 * 1000,
    maxSize: 512,
    updateExpire: false
})
const moized = moizer(message => message)

server.on('error', err => {
    const { message } = err
    let level = 'error'

    if (moized.get(message))
        level = 'warn'
    else
        moized.add(message)

    // ...
```

**Comment by Redsandro** [comment]
My fault. `.get()` should be array.

`moized.get(message)` => `moized.get([message])`.

Error message thrown could be more to the point. E.g. in stead of this:

> CreateListFromArrayLike called on non-object

Perhaps moize can check or catch to say this:

> Array expected. String given.

**Comment by Redsandro** [comment]
Feel free to either keep as feature request because it is helpful, or close because people should read the manual better.

**Comment by planttheidea** [comment]
Glad you were able to sort this out!

I can definitely look into better error messaging on those cache manipulators. I'm in the final stages of v6 (TypeScript rewrite), basically just documentation, so I can easily slide this in.

**Comment by Redsandro** [comment]
Thank you!
